### ISSUE TITLE
Failed to resolve: com.github.paroca72:sc-gauges:2.6.7

### ISSUE THREAD

**Issue by dondeepak** [Paroca72/sc-gauges#10]
i cant sync build gradle i am getting error please help
 Failed to resolve: com.github.paroca72:sc-gauges:2.6.7

**Comment by Paroca72** [comment]
Hello,

Thanks for your advise..
Seem as jitpack not work anymore with gradle 3.0 without apply some config update.. but following the instruction I not able so solve it..

So revert to 2.6.6 version meanwhile I will have time to take in charge this issue..

Thanks
Sam

**Comment by dondeepak** [comment]
thank you

**Comment by dondeepak** [comment]
i have another question. in my app i get vehicle speed 30 sec once i want to move indicator for example  my vehicle speed is 50 after 30sec its speed is 60 so i wanted to animate indicator 
   ist=(int)prespeed;
                                ien=(int)currspeed;
                                for (;ist<=ien;ist++) {
                                    int Itrspeed = ist;
                                    angleg = gauge.percentageToAngle(Itrspeed);
                                    indicator.setRotation(angleg);
                                    counter.setText("" + Itrspeed + ""); 

but indicator is not animating(51,52,53,etc..) it only shows last speed(60).

**Comment by Paroca72** [comment]
Hello,

The gauge has already implemented the values animation..
You can refer to [ScGauge](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-gauge/ScGauge.md) guide.

So first we must apply the indicator rotation in the classic way using the gauge listener as follow:
```
     // Each time I will change the value I must write it inside the counter text.
    gauge.setOnEventListener(new ScGauge.OnEventListener() {
        @Override
        public void onValueChange(float lowValue, float highValue) {
            // Convert the percentage value in an angle
            float angle = gauge.percentageToAngle(highValue);
            indicator.setRotation(angle);
        }
    });
```

Second we must get back the value [Animator](https://developer.android.com/reference/android/animation/Animator.html) (have two high and low same the default pointers) and apply a duration (in milliseconds):

```
Animator animator = gauge.getHighValueAnimator();
animator.setDuration(1000);
```

Now the indicator will move from-to in one second animating..

Please note that with the Animator object you can change also the animation type using the `setInterpolator` method and other..

I hope this can help you
Sam

**Comment by Paroca72** [comment]
Hello,

It seems the Gradle 3.0.0 is not more compatible with the jitpack without some new settings..
I tried with following the documentation but I not be able to solve it.

I reverted the Gradle to the 2.3.3 version and upload a new version and now seems to compile it without problems.
Try to download the latest version 2.6.10 this sould be work..

Thanks
Sam
