### ISSUE TITLE
360 degree scArcGauge  left a blake tail

### ISSUE THREAD

**Issue by turtlenosleep** [Paroca72/sc-gauges#11]
Hi,
I am using sc-gauges:2.6.6, and I have a scArcGauge with angleStart =65 ,angleSweep=360,
color array int[140],0 - 19 120 - 139 are white,else are filled with red,green,yellow.
there will be a balke tail in the end of ring like this
![1](https://user-images.githubusercontent.com/15650383/32925703-473dc51e-cb7e-11e7-9916-2e18970aa6ee.png)

if I didn't set angleSweep，the result is the same,I try to fix this ,so I extend ScCopier 
and override createColoredBitmap like this
![2](https://user-images.githubusercontent.com/15650383/32925758-86ffd4b2-cb7e-11e7-9b3f-b68b7783dbb2.png)

and it works,black tail is gone~
![3](https://user-images.githubusercontent.com/15650383/32925764-91903246-cb7e-11e7-8084-5c27554fc6ef.png)

I dont know if this is a issue or I didn't set ScArcGauge right, wish be helpfual~:D

**Comment by Paroca72** [comment]
Hello,

Try to download the latest version 2.6.10 and let me know if this solve this issue..

Thanks
Sam

**Comment by turtlenosleep** [comment]
Hi~
I upgrade to 2.6.10 and this is fixed,thanks you~~
