### ISSUE TITLE
Little help placing a feature/pointer along curve

### ISSUE THREAD

**Issue by rickAllDev** [Paroca72/sc-gauges#12]
Just started playing with you're library and I'm confused on how to user the feature/pointer.

I'm using the ArcGuage and trying to place an indicator along the guage, for example, indicating the speed limit. Not worried about what the indicator looks like yet (a line, arrow, etc.). Could you point me in the right direction?

**Comment by Paroca72** [comment]
Hello,

Please take a look to [Example 4](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/flat.md).
In this you will see two pointer along the path. In your case you can avoid to make the "low" pointer visible so avoid to write this line of code: `gauge.setPointerLowVisibility(true);` 
After that the "high" pointer follow the position on path given throught the `gauge.setHighValue(...);` or via XML.

Please note than the [ScPointer](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-pointer/ScPointer.md) allow you to use a bitmap instead a circle..
For do this please follow the [Example 5](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-lineargauge/flat.md) in the ScLinearGauge section..
ScLinearGauge and ScArcGauge inherit from the same class so all code is portable from one to another..

Let me know is this info help you
Sam

**Comment by rickAllDev** [comment]
still struggling with this. I see that I need to use scPointer but trouble associating.
ScArcGauge gauge;
ScPointer pointer; - how do i associate with gauge path? The example shows it being associated in the onDrawListener - do I need to use?
pointer.info.bitmap allows me to set my graphic
if I want to draw the graphic at a point along the curve, how do i set that point? Will offsetting offset perpendicular to the curve?
Can I get the graphic to rotate at the same angle as the gauge, i.e. stay perpendicular to the curve

The best example of what I'm trying to do is a speedometer with a graphic indicating the speed limit that is sitting above the gauge with the ability to change the speed limit.

**Comment by Paroca72** [comment]
Hello,

The ScArcGauge class make (almost) all for you.
Its enough follow the example than you can find here [Example 2](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/notches.md)
The part to take care for your case is:

```
        ...        
        @Override
        public void onBeforeDrawPointer(ScPointer.PointerInfo info) {
            // Check if the pointer if the high pointer
            if (info.source.getTag() == ScGauge.HIGH_POINTER_IDENTIFIER) {
                // Adjust the offset
                info.offset.x = -indicator.getWidth() / 2;
                info.offset.y = -indicator.getHeight() / 2 - gauge.getStrokeSize();
                // Assign the bitmap to the pointer info structure
                info.bitmap = indicator;
            }
        }
        ...
```

This methods load the bitmap (in the right position) that you want as indicator already rotated and apply to it a custom offset.
Note than the position of the indicator on the path depends by the ScArcGaguge high value.
You can use `gauge.setHighValue(your value);` for drive your indicator.
 
If you want have a custom rotation (angle) you can use, in the above methods, the `info.angle` property..
Please refer to the [OnDrawListener](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-pointer/ScPointer.md) of the ScPointer class for other properties than you can change.

Regards
Sam
