### ISSUE TITLE
Attributes missing

### ISSUE THREAD

**Issue by EnricoBeltramo** [Paroca72/sc-gauges#14]
Hello,
I tried the example 4 , but I have some build issue due attribute missing (ever using the demo project).
Did I miss something?

Here the log:

Android resource linking failed
Output:  D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute angleStart (aka com.sccomponents.demo:angleStart) not found.
D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute angleSweep (aka com.sccomponents.demo:angleSweep) not found.
D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute progressColors (aka com.sccomponents.demo:progressColors) not found.
D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute progressSize (aka com.sccomponents.demo:progressSize) not found.
D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute strokeColor (aka com.sccomponents.demo:strokeColor) not found.
D:\Progetti\Faplab\BiciElettrica\sc-gauges\app\src\main\res\layout\activity_main.xml:6: error: attribute strokeSize (aka com.sccomponents.demo:strokeSize) not found.
error: failed linking file resources.

Thank

**Comment by Paroca72** [comment]
Hello Enrico,

Where you found the example 4?
In any case please use "scc" prefix for all the attributes.
sccAngleStart
sccAngleSweep
sccProgressColors
...
...

Thanks
Sam

**Comment by EnricoBeltramo** [comment]
Hello,

I referred to example list in this page (I don't know if is still valid):
https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/notches.md

Thank you, I will try as soon possible.

**Comment by Paroca72** [comment]
Ciao Enrico,

That example was referred to the 2.x version..
You will have for sure some problem with the 3.x version..

If I will find 5 minutes I will try to adapt this example with the 3.x library for you.

Sam

**Comment by Paroca72** [comment]
Ciao Enrico,

I rewrote the example using the 3.x version library.

XML

    <FrameLayout
        android:layout_width="300dp"
        android:layout_height="wrap_content"
        android:background="#f5f5f5">

        <com.sccomponents.gauges.library.ScArcGauge
            android:id="@+id/gauge"
            xmlns:sc="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:padding="10dp"
            sc:sccAngleStart="-180"
            sc:sccAngleSweep="90"
            />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:gravity="right"
            android:layout_gravity="bottom|right"
            android:layout_marginRight="10dp">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="#b6c2d5"
                android:textSize="20dp"
                android:text="speedometer"
                android:gravity="center"
                />

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:id="@+id/counter"
                android:textColor="#787b80"
                android:textSize="40dp"
                android:textStyle="bold"
                android:text="0"
                android:gravity="center"
                android:paddingLeft="10dp"/>

        </LinearLayout>

    </FrameLayout>

CODING

        // Find the components
        final ScArcGauge gauge = (ScArcGauge) this.findViewById(R.id.gauge);
        assert gauge != null;

        final TextView counter = (TextView) this.findViewById(R.id.counter);
        assert counter != null;

        // Clear all default features from the gauge
        gauge.removeAllFeatures();

        // Create the base notches.
        ScNotches base = (ScNotches) gauge.addFeature(ScNotches.class);
        base.setTag(ScGauge.BASE_IDENTIFIER);
        base.setPosition(ScFeature.Positions.INSIDE);
        base.setRepetitions(40);
        base.setWidths(10);
        base.setHeights(10, 120);
        base.setColors(Color.parseColor("#dbdfe6"));

        // Create the progress notches.
        ScNotches progress = (ScNotches) gauge.addFeature(ScNotches.class);
        progress.setTag(ScGauge.PROGRESS_IDENTIFIER);
        progress.setColors(
                Color.parseColor("#0BA60A"),
                Color.parseColor("#FEF301"),
                Color.parseColor("#EA0C01")
        );

        // Set the value
        gauge.setHighValue(12000, 0, 13000);

        // Each time I will change the value I must write it inside the counter text.
        gauge.setOnEventListener(new ScGauge.OnEventListener() {
            @Override
            public void onValueChange(float lowValue, float highValue, boolean isRunning) {
                // Write the value
                int value = (int) ScGauge.percentageToValue(highValue, 0, 13000);
                counter.setText(Integer.toString(value));
            }
        });


Regards
Sam

**Comment by EnricoBeltramo** [comment]
Hello,
I tested: it works perfectly now.

Thank you very much for the support
