### ISSUE TITLE
gauge.setTextTokens is not defined

### ISSUE THREAD

**Issue by Sowjanyaprao** [Paroca72/sc-gauges#15]
When I followed the example for ScArcGauge examples I got error saying setTextTokens method is not found

**Comment by Paroca72** [comment]
Examples???? For the 3.x version is still not implement any examples.
So maybe you found some old examples on the net.. sorry for this.

I can suggest you to use the last documentation than you can find in home page or at the following link:
https://paroca72.github.io/sc-gauges/reference/packages.html

About setTextTokens I think now is called setTokens.. if you are using ScWriter feature.
But I think it will not the only changes than you must do for make the example work.
So maybe its better if you link me the example and I will back a working one.

Please let me know
Sam

**Comment by Sowjanyaprao** [comment]
Thanks for replying Sam.
I was trying "Example 1" from below link -( Search for gauge.setTextTokens )
https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/notches.md

And added below line in build.gradle
allprojects {
	repositories {
		maven { url "https://jitpack.io" }
	}
}

Added in dependency
dependencies {
    compile 'com.github.paroca72:sc-gauges:3.1.3'
}

But it never worked. I found all the widgets nice so was trying to add this widget in my project.
It will be helpful if you provide the working example.

Thanks
Sowjanya

**Comment by Paroca72** [comment]
Here the code..
Please download the last release 3.1.4 as I changed some feature for work with this example.


        // Find the components
        final ScArcGauge gauge = (ScArcGauge) this.findViewById(R.id.gauge);
        assert gauge != null;

        final ImageView indicator = (ImageView) this.findViewById(R.id.indicator);
        assert indicator != null;

        // Set the center pivot for a right rotation
        indicator.setPivotX(39);
        indicator.setPivotY(88);

        // Set the filter of the base
        BlurMaskFilter filter = new BlurMaskFilter(10, BlurMaskFilter.Blur.INNER);
        ScCopier base = gauge.getBase();
        base.getPainter().setMaskFilter(filter);

        // Writer
        String[] tokens = new String[11];
        for (int index = 0; index < 11; index++) {
            tokens[index] = Integer.toString((index + 1) * 10);
        }

        ScWriter writer = gauge.getWriter();
        writer.setRepetitionOffset(50);
        writer.setTokens(tokens);

        // Notches
        ScNotches notches = gauge.getNotches();
        notches.setRepetitions(tokens.length);

        // Set the values.
        gauge.setHighValue(60);

        // Each time I will change the value I must write it inside the counter text.
        gauge.setOnEventListener(new ScGauge.OnEventListener() {
            @Override
            public void onValueChange(float lowValue, float highValue, boolean isRunning) {
                // Convert the percentage value in an angle
                float angle = gauge.percentageToAngle(highValue);
                indicator.setRotation(angle);
            }
        });

        gauge.setOnDrawListener(new ScGauge.OnDrawListener() {
            @Override
            public void onDrawContour(ScFeature.ContourInfo info) {
                // NOP
            }

            @Override
            public void onDrawRepetition(ScRepetitions.RepetitionInfo info) {
                if (info instanceof ScNotches.NotchInfo) {
                    ScNotches notches = ((ScNotches.NotchInfo) info).source;
                    info.offset[1] = gauge.dipToPixel(6);
                    info.visible = info.repetition > 1 && info.repetition < notches.getRepetitions();
                }

                if (info instanceof ScWriter.TokenInfo) {
                    // Offset
                    info.offset[1] = - gauge.dipToPixel(8);

                    // Highlight
                    int sector = (int) (gauge.getHighValue() / 10);
                    info.color = sector == info.repetition ?
                            Color.BLACK : Color.parseColor("#cccccc");
                }
            }
        });



<FrameLayout
        android:layout_width="300dp"
        android:layout_height="wrap_content"
        android:background="#f5f5f5">

        <com.sccomponents.gauges.library.ScArcGauge
            android:id="@+id/gauge"
            xmlns:sc="http://schemas.android.com/apk/res-auto"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:padding="35dp"
            sc:sccAngleStart="180"
            sc:sccAngleSweep="180"
            sc:sccStrokeColors="#03A409|#FFF506|#EB0100"
            sc:sccStrokeWidth="32dp"
            sc:sccStrokePosition="inside"
            sc:sccNotchesHeight="20dp"
            sc:sccNotchesWidth="2dp"
            sc:sccNotchesPosition="inside"
            sc:sccNotchesColor="#666666"
            sc:sccTextAlign="center"/>

        <ImageView
            android:id="@+id/indicator"
            android:layout_width="120dp"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|center_horizontal"
            android:src="@drawable/indicator"
            android:layout_marginLeft="40dp"
            android:layout_marginBottom="9dp"/>

    </FrameLayout>

**Comment by Sowjanyaprao** [comment]
Thanks for the updated code Sam, its working now.
