### ISSUE TITLE
getPathMeasure().getLength() issue

### ISSUE THREAD

**Issue by lukpie** [Paroca72/sc-gauges#16]
Hi Sam,

I am struggeling to get getPathMeasure().getLength() to work properly when I set setFillingArea to anything else then NONE - the resulting lenght is always the same as if it was set to NONE, the change due to the "stretching" seems not to be taken into acocunt.

Any ideas?

**Comment by Paroca72** [comment]
Hello Luk,

The getPathMeasure() return an PathMeasure object extended.
As the PathMeasure do just give you back the length of the associated path but before drawn on canvas.
So all the way to draw the path on canvas (setFillingArea) not have effect on this value.

If you want to know the length of the path after stretched or something like this I think is not possible cause, if you look inside the ScDrawer class, you can find

    private void drawFeatures(Canvas canvas, Matrix matrix) {
        // Check for empty values
        if (this.mFeatures != null) {
            // Cycle all features
            for (ScFeature feature : this.mFeatures)
                // Check for empty value
                if (feature != null) {
                    //Call the draw methods.
                    feature.setDoubleBuffering(this.mDoubleBuffering);
                    feature.applyMatrixToCanvas(matrix);
                    feature.draw(canvas);
                }
        }
    }

The transformation is applied on the canvas and not on the path.

Sam
