### ISSUE TITLE
Start and end do not connect

### ISSUE THREAD

**Issue by s-ilnar** [Paroca72/sc-gauges#17]
The end of the line does not connect with the beginning. How can I fix it?

<img src="https://i.ibb.co/9tRDtX0/Screenshot-2019-06-20-14-41-54-268-ru-quantor-pre77-phone.png" alt="Screenshot-2019-06-20-14-41-54-268-ru-quantor-pre77-phone" border="0" />

my layout code:

```
    <com.sccomponents.gauges.library.ScArcGauge
        android:id="@+id/progressBar"
        android:layout_width="180dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="50dp"
        android:padding="10dp"
        app:scPathTouchable="true"
        app:sccAngleStart="270"
        app:sccNotchesHeight="10dp"
        app:sccNotchesWidth="10dp"
        app:sccProgressColor="#3DB8B7"
        app:sccProgressRoundedCap="true"
        app:sccProgressWidth="8dp"
        app:sccSnapToNotches="true"
        app:sccStrokeColor="@color/rating_no_active_color"
        app:sccStrokeWidth="6dp"
        app:sccValue="70"
        />
```

**Comment by s-ilnar** [comment]
> The end of the line does not connect with the beginning. How can I fix it?
> 
> <img src="https://i.ibb.co/9tRDtX0/Screenshot-2019-06-20-14-41-54-268-ru-quantor-pre77-phone.png" alt="Screenshot-2019-06-20-14-41-54-268-ru-quantor-pre77-phone" border="0" />
> 
> my layout code:
> 
> ```
>     <com.sccomponents.gauges.library.ScArcGauge
>         android:id="@+id/progressBar"
>         android:layout_width="180dp"
>         android:layout_height="wrap_content"
>         android:layout_marginTop="50dp"
>         android:padding="10dp"
>         app:scPathTouchable="true"
>         app:sccAngleStart="270"
>         app:sccNotchesHeight="10dp"
>         app:sccNotchesWidth="10dp"
>         app:sccProgressColor="#3DB8B7"
>         app:sccProgressRoundedCap="true"
>         app:sccProgressWidth="8dp"
>         app:sccSnapToNotches="true"
>         app:sccStrokeColor="@color/rating_no_active_color"
>         app:sccStrokeWidth="6dp"
>         app:sccValue="70"
>         />
> ```

**Comment by Paroca72** [comment]
Please try to download the latest version

**Comment by s-ilnar** [comment]
Sorry, but I put the wrong screenshot. Here is the right one.

<img src="https://i.ibb.co/9g1jVz8/Screenshot-2019-06-20-14-44-20-352-ru-quantor-pre77-phone.png" alt="Screenshot-2019-06-20-14-44-20-352-ru-quantor-pre77-phone" border="0">

Is it possible to make the beginning and the end connected?
Like here:

<img src="https://i.ibb.co/FnWHQ1p/Screenshot-2019-06-20-14-44-20-352-ru-quantor-pre77-phone-png2.png" alt="Screenshot-2019-06-20-14-44-20-352-ru-quantor-pre77-phone-png2" border="0">


Maybe there is a parameter, app:sccProgressFullConcat="true" ?

**Comment by Paroca72** [comment]
You cannot..
But you can try with a trick

        final Button button = this.findViewById(R.id.button);
        assert button != null;

        gauge.setOnEventListener(new ScGauge.OnEventListener() {
            @Override
            public void onValueChange(ScGauge gauge, float lowValue, float highValue, boolean isRunning) {
                Paint.Cap cap = highValue == 100.0f ? Paint.Cap.SQUARE: Paint.Cap.ROUND;
                gauge.getProgress().getPainter().setStrokeCap(cap);
            }
        });

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                gauge.setHighValue(100);
            }
        });

**Comment by s-ilnar** [comment]
Thanks man!!
