### ISSUE TITLE
how to add progress point to progress line

### ISSUE THREAD

**Issue by s-ilnar** [Paroca72/sc-gauges#19]
how to add progress point to progress line?
<img src="https://i.ibb.co/4gGrCKx/point.png" alt="point" border="0">

**Comment by Paroca72** [comment]
Please take a look to the ScPointer class.

        ScPointer pointer = gauge.getHighPointer();
        pointer.setVisible(true);
        pointer.setHeights(50);
        pointer.setWidths(50);
        pointer.setColors(Color.parseColor("#3DB8B7"));

Thanks

**Comment by s-ilnar** [comment]
thanks!
