### ISSUE TITLE
gauge doesnt work 

### ISSUE THREAD

**Issue by saiidabs** [Paroca72/sc-gauges#2]
copied the example you have ScArcGauge
with this dependency 
    compile 'com.github.paroca72:sc-gauges:2.6.0'

and i get this problem when running the application
![image](https://user-images.githubusercontent.com/10105522/28489423-037ee75a-6f07-11e7-9333-e352fc717f96.png)
![image](https://user-images.githubusercontent.com/10105522/28489443-50e1cfe4-6f07-11e7-9265-81a9c657ba5b.png)

when i add 
sc:scc_angle_start="135"
 sc:scc_angle_sweep="270"

i get this error
![image](https://user-images.githubusercontent.com/10105522/28489521-03d6fbce-6f08-11e7-9167-d5572b097cd5.png)

**Comment by Paroca72** [comment]
Hello,

Sorry for this issue..
I had miss to update some documentation files after change from the 2.5 to 2.6 version..
Please use `angleStart` and `angleSweep` instead the properties you used before..

You can refer to this page as listed 
[ScArcGauge](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/ScArcGauge.md)

Please let me know if this solve your case.

Regards
Samuele

**Comment by saiidabs** [comment]
still get the same issue, here is the xml , here is where the gauge resides 
<FrameLayout
                        android:layout_width="160dp"
                        android:layout_height="160dp">

                        <com.sccomponents.gauges.ScArcGauge
                            xmlns:sc="http://schemas.android.com/apk/res-auto"
                            android:id="@+id/gauge"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:padding="10dp"
                            android:background="#f5f5f5"
                            sc:angleStart="135"
                            sc:angleSweep="270"
                            sc:strokeSize="6dp"
                            sc:progressSize="4dp"
                            sc:value="45"
                            sc:notches="8"
                            sc:notchesLength="10dp"
                            sc:textTokens="01|02|03|04|05|06|07|08"
                            sc:pointerRadius="10dp"/>

                        <ImageView
                            android:id="@+id/indicator"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_alignParentLeft="false"
                            android:layout_gravity="center"
                            android:padding="20dp"
                            android:scaleType="fitCenter"
                            android:src="@drawable/indicator_04" />


                        <TextView
                            android:id="@+id/counter"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_gravity="center"
                            android:padding="10dp"
                            android:text="0"
                            android:textColor="#ffffff"
                            android:textSize="20dp"
                            android:textStyle="bold" />


                    </FrameLayout>

and still get this error
![image](https://user-images.githubusercontent.com/10105522/28496046-38a1844a-6fa4-11e7-8c2c-d8516a9caebd.png)

**Comment by saiidabs** [comment]
yea changed it and still , i get these errors
![image](https://user-images.githubusercontent.com/10105522/28496252-1af51212-6faa-11e7-838f-565cfd5da627.png)

**Comment by Paroca72** [comment]
Hello,

Can you give to me your xml code?

Sam

**Comment by saiidabs** [comment]
<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:sc="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.globalkenticscorp.pkg.testActiviy"
    tools:showIn="@layout/activity_test_activiy"

    android:orientation="horizontal"
    tools:layout_editor_absoluteY="8dp"
    tools:layout_editor_absoluteX="8dp">

        <com.sccomponents.gauges.ScArcGauge
            android:id="@+id/scArcGauge"
            android:layout_width="395dp"
            android:layout_height="587dp"
            android:background="#f5f5f5"
            android:padding="30dp"
            sc:angleStart="135"
            sc:angleSweep="270"
            sc:notches="8"
            sc:notchesLength="10dp"
            sc:pointerRadius="10dp"
            sc:progressSize="4dp"
            sc:strokeSize="6dp"
            sc:textTokens="01|02|03|04|05|06|07|08"
            sc:value="45"
            tools:layout_editor_absoluteX="8dp"
            tools:layout_editor_absoluteY="8dp" />
    </LinearLayout>

**Comment by saiidabs** [comment]
i thought maybe what i was customising it prommatically was wrecking it, so i creating an new activity with the gauge in the layout file , so i can see if a plain one works but it doesnt, i get that 
"                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sccomponents.gauges.e.a(java.lang.String)' on a null object reference
"

**Comment by Paroca72** [comment]
Hello,

For the XML
I guess you are trying to use it inside `ConstraintLayout`.. so i think is better not mixing different layouts properties..

```
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:sc="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.sccomponents.gauges.ScArcGauge
        android:id="@+id/scArcGauge"
        android:layout_width="368dp"
        android:layout_height="495dp"
        android:background="#f5f5f5"
        android:padding="30dp"
        sc:angleStart="135"
        sc:angleSweep="270"
        sc:notches="8"
        sc:notchesLength="10dp"
        sc:pointerRadius="10dp"
        sc:progressSize="4dp"
        sc:strokeSize="6dp"
        sc:textTokens="01|02|03|04|05|06|07|08"
        sc:value="45"
        android:layout_marginLeft="8dp"
        sc:layout_constraintLeft_toLeftOf="parent"
        android:layout_marginRight="8dp"
        sc:layout_constraintRight_toRightOf="parent"
        sc:layout_constraintTop_toTopOf="parent"
        android:layout_marginTop="8dp"
        sc:layout_constraintBottom_toBottomOf="parent"
        android:layout_marginBottom="8dp" />

</android.support.constraint.ConstraintLayout>
```

On my emulator this work..
Same with case of LinearLayout and FrameLayout as in the online documentation example..

So if you have some NULL references programmatically better if you write me back your code part refer to Gauge setup..

Waiting for your code

Thanks
Sam

**Comment by saiidabs** [comment]
Hi ,sorry the underlining issue was multidex , sorry . thanks for your help

**Comment by Paroca72** [comment]
You are welcome
