### ISSUE TITLE
how to show textual information about progress

### ISSUE THREAD

**Issue by s-ilnar** [Paroca72/sc-gauges#20]
I could not find a standard method that will show the value of progress as in the picture. help me please.

<img src="https://i.ibb.co/njBZ2s6/f-02.jpg" alt="f-02" border="0"></a>

Or should I add TextView myself?

**Comment by Paroca72** [comment]
final TextView text = this.findViewById(R.id.textView);
        assert text != null;

        gauge.setOnEventListener(new ScGauge.OnEventListener() {
            @Override
            public void onValueChange(ScGauge gauge, float lowValue, float highValue, boolean isRunning) {
                text.setText(Float.toString(highValue));
            }
        });

**Comment by s-ilnar** [comment]
thank. Yes, I did. but I thought that inside ScGauge there is the possibility of installing such a text

**Comment by Paroca72** [comment]
Yes you can using
ScLabeler: write the current value at the end of the progress bar
ScWriter: write many labels on the gauges

**Comment by Paroca72** [comment]
ScLabeler labeler = gauge.getLabeler();
        labeler.setVisible(true);
        labeler.setBackground(Color.WHITE);
        labeler.setPadding(10);

        ScWriter writer = gauge.getWriter();
        writer.setTokens("1", "2", "3", "4");
