### ISSUE TITLE
how to set gauge colors (like example 2 in notches.md)

### ISSUE THREAD

**Issue by hahn** [Paroca72/sc-gauges#22]
Hello, i tried follow example 2 from [here](https://github.com/Paroca72/sc-gauges/blob/master/raw/sc-arcgauge/notches.md) . unfortunately I can't set colors to gauge. How to set the color? 

And where I can find example for version 3.xx?

thanks in advance.

**Comment by Paroca72** [comment]
Hello,

That examples is not for the 3.x version.. So I not recommend you to use as you will encounter in many problems..
Unfortunately I no have time to carry on this project with some example so I can suggest you to refer to the [documentation ](https://paroca72.github.io/sc-gauges/reference/com/sccomponents/gauges/library/package-summary.html) online.

About the color all the features as the method `setColors` than permit to set the colors.
So you can simple get your feature and set its with this method, for example for the base copier:
`mGauge.getBase().setColors(Color.White, Color.Black);`

You can also define every features color using the `xml` properties of [ScArcGauge](https://paroca72.github.io/sc-gauges/reference/com/sccomponents/gauges/library/ScGauge.html)

Sam
