### ISSUE TITLE
Proguard Problem

### ISSUE THREAD

**Issue by turtlenosleep** [Paroca72/sc-gauges#3]
If I use Proguard to obfuscate My Code,it will crash because ScGauge 281~296 get null reference when trying to get ScFeatures,so  I add proguard rule

-keep public class * extends com.sccomponents.gauges.ScFeature{
    public <methods>;
}

to fix this,maybe you could write more precise rule in ReadMe.md~ : )

**Comment by Paroca72** [comment]
Hello Turtle,

Thanks for your reporting..

At now I still not had this kind of issue so I will thanks you if you can give me some extra information for try to fix it within.

Some info like:
- You have the bug only when you enable the minify?
- What API version?
- Maybe you saved a screenshot of the error log?

Very thanks for your support
Sam
