### ISSUE TITLE
Writing to a gauge when two are in a view causes exception and crash

### ISSUE THREAD

**Issue by robhellstrom** [Paroca72/sc-gauges#4]
Hi I have two ScArcGauges in two different constraint layouts in the same screen, one set to invisible.

I update both in real time with a background process so they are correct when they become visible based on buttons selected by the user.

This seems to crash the app. When I remove one or both I never see the crash.

Happy to provide more details - but is this by design?

**Comment by Paroca72** [comment]
Hello Rob,

Thanks for your report..
Can you give me back the log of the error?

Thanks
Sam

**Comment by robhellstrom** [comment]
Apologies was writing to a textView widget within the constraint that was null sometimes.

**Comment by Paroca72** [comment]
No problem.. happen..
So I will close this issue.

Bye
Sam
