### ISSUE TITLE
Incorrect starting angle on Android 8.0 API 26

### ISSUE THREAD

**Issue by dpeters1** [Paroca72/sc-gauges#5]
The start angle for circular gauges seems to be double of what it used to be, and has weird behaviour. In both snapshots, the start angle is set programmatically to 90*, but on API 26 it starts at 180*. Furthermore, setting it to 45* causes the gauge to not render, and at 135* it renders as an oval.

API 24  `powerGauge.setAngleStart(90);`
![arcgauge24](https://user-images.githubusercontent.com/11788854/30043163-de44268c-91c3-11e7-8e89-d701686ef881.PNG)

API 26  `powerGauge.setAngleStart(90);`
![arcgauge26](https://user-images.githubusercontent.com/11788854/30043162-de435a90-91c3-11e7-83d1-39fd7a7deb49.PNG)

API 26  `powerGauge.setAngleStart(135);`
![arcgauge26-135](https://user-images.githubusercontent.com/11788854/30043277-82173498-91c4-11e7-9537-f0936b84f6a6.PNG)

**Comment by Paroca72** [comment]
Hello Peter,

Thanks for your advise..
Try to download the latest version (2.6.2) the issue should be solved.

Let me know
Bye

**Comment by dpeters1** [comment]
Resolved, thanks for the quick response!
