### ISSUE TITLE
Not able to set a TypeFace to text tokens

### ISSUE THREAD

**Issue by EtienneSultan** [Paroca72/sc-gauges#6]
Is there any way to set a custom typeface ?

**Comment by Paroca72** [comment]
Hello Etienne,

You can recover the ScWriter feature inside your guage like this:

`ScFeature writer = gauge.findFeature(ScGauge.WRITER_IDENTIFIER);`

From the feature you can get the Painter object and apply the font type face:

```
Paint painter = writer.getPainter();
painter.setTypeface(...);
```
If you do this after the first render you will need to force the gauge repaint calling an invalidate like this:

`gauge.invalidate();`

Let me know if this solve your problem.
Bye

**Comment by EtienneSultan** [comment]
Hi, thanks a lot for your fast answer, it totally solves my problem, I am not yet very used to the Painter class !
