### ISSUE TITLE
Round cap not applied when using multiple colors in ScArcGauge

### ISSUE THREAD

**Issue by eleddie** [Paroca72/sc-gauges#9]
When applying multiple colors to the Arc gauge the starting cap is not round:
```
gauge.findFeature(ScArcGauge.PROGRESS_IDENTIFIER).painter.strokeCap = Paint.Cap.ROUND
```
and
```
app:progressColors="#FFEB3B|#4CAF50|#F44336"
```
Gives this:
![gauge](https://user-images.githubusercontent.com/13477629/31856595-1c9c060e-b693-11e7-9c46-f9ee73bcfac8.jpeg)

And if the arc is complete:
![gauge2](https://user-images.githubusercontent.com/13477629/31856618-a4f6fe3c-b693-11e7-8a86-bcfc82ff44a0.jpeg)

Any ideas?

**Comment by Paroca72** [comment]
Hello,

Sorry for the late reply..

I seen the issue but at moment I have my laptop not stay on for more than 5 minutes so I cannot help you. In the end of week I should go to buy a new one and I will fix this issue.. so sorry.

Thanks
Sam

**Comment by Paroca72** [comment]
Hello,

Thanks for patient and sorry for the long waiting..
Plase try to download the latest version (2.6.6) and let me know if this patch solve your issue.

Thanks
Sam

**Comment by eleddie** [comment]
Hi @Paroca72! I tested it and it's working almost perfectly. Here are some screenshots:

![arcgauge](https://user-images.githubusercontent.com/13477629/32056009-738451d2-ba31-11e7-80fc-651619714f08.jpeg)
![arcgauge2](https://user-images.githubusercontent.com/13477629/32056010-739de0b6-ba31-11e7-859a-6bb6c60cba07.jpeg)

**Comment by Paroca72** [comment]
Hello,

Try (again) with the latest version (2.6.7) and let me know.

Thanks
Sam

**Comment by eleddie** [comment]
I get:
```Failed to resolve: com.github.paroca72:sc-gauges:2.6.7```
I might need to wait some time.

I'll let you know. Thanks!

**Comment by eleddie** [comment]
Hey @Paroca72 how's it going?
Still can't update to latest version. Any updates?

**Comment by Paroca72** [comment]
Hello,

It seems the Gradle 3.0.0 is not more compatible with the jitpack without some new settings..
I tried with following the documentation but I not be able to solve it.

I reverted the Gradle to the 2.3.3 version and upload a new version and now seems to compile it without problems.
Try to download the latest version 2.6.10 this sould be work..

Thanks
Sam

**Comment by eleddie** [comment]
Works perfectly! Thank you so much!
